;;; agentedit-readable-tests.el --- Readable frame regressions -*- lexical-binding: t; -*-

(require 'json)

(defconst agentedit-readable-test--corpus
  (let ((json-object-type 'alist) (json-array-type 'list)
        (json-key-type 'symbol))
    (json-read-file
     (expand-file-name "../fixtures/readable-edits.json"
                       (file-name-directory (or load-file-name buffer-file-name))))))

(defun agentedit-readable-test--fixture (id)
  (cl-find id (alist-get 'valid agentedit-readable-test--corpus)
           :key (lambda (f) (alist-get 'id f)) :test #'equal))

(ert-deftest agentedit-readable-corpus-payloads-resolution-and-undo ()
  (dolist (fixture (alist-get 'valid agentedit-readable-test--corpus))
    (dolist (side '(accepted rejected))
      (ert-info ((format "%s %s" (alist-get 'id fixture) side))
		(agentedit-review-test--with-source (alist-get 'source fixture)
		  (let* ((records (agentedit-review--scan-records (point-min)))
			 (record (car records))
			 (session (agentedit-review--make-session :source (current-buffer) :records records)))
		    (should (= (length records) 1))
		    (should (agentedit-review-record-framed record))
		    (should (equal (agentedit-review-record-original record) (alist-get 'original fixture)))
		    (should (equal (agentedit-review-record-edited record) (alist-get 'proposed fixture)))
		    (should (equal (agentedit-review-record-whitespace record) (alist-get 'whitespace fixture)))
		    (agentedit-review--replace-current session
						       (alist-get (if (eq side 'accepted) 'proposed 'original) fixture))
		    (should (equal (buffer-string) (alist-get side fixture)))
		    (should (buffer-modified-p))
		    (undo-only 1)
		    (should (equal (buffer-string) (alist-get 'source fixture)))))))))

(ert-deftest agentedit-readable-corpus-malformed-and-opaque ()
  (dolist (fixture (alist-get 'invalid agentedit-readable-test--corpus))
    (ert-info ((alist-get 'id fixture))
	      (let ((error-data (should-error (agentedit-review-test--records (alist-get 'source fixture)) :type 'user-error)))
		(should (string-match-p (alist-get 'error_category fixture) (error-message-string error-data))))))
  (dolist (fixture (alist-get 'opaque agentedit-readable-test--corpus))
    (ert-info ((alist-get 'id fixture))
	      (should-not (agentedit-review-test--records (alist-get 'source fixture)))
	      (should (= 1 (length (agentedit-review-test--records
				    (concat (alist-get 'source fixture) "\n"
					    (alist-get 'source (agentedit-readable-test--fixture "word"))))))))))

(ert-deftest agentedit-readable-origin-anywhere-in-owned-frame ()
  (let* ((f (agentedit-readable-test--fixture "word"))
         (start (1+ (length (alist-get 'prefix f))))
         (end (+ start (length (alist-get 'frame f)))))
    (cl-loop for origin from start below end do
             (should (equal (agentedit-review-test--ids
                             (agentedit-review-test--records (alist-get 'source f) origin)) '("word"))))
    (should-not (agentedit-review-test--records (alist-get 'source f) end))))

(ert-deftest agentedit-readable-stale-envelope-and-context ()
  (let ((f (agentedit-readable-test--fixture "word")))
    (dolist (needle '("always" "START" "END" "The" "terminates"))
      (agentedit-review-test--with-source (alist-get 'source f)
	(let* ((records (agentedit-review--scan-records (point-min)))
	       (session (agentedit-review--make-session :source (current-buffer) :records records)))
	  (goto-char (point-min)) (search-forward needle) (backward-char (length needle)) (insert "changed")
	  (let ((changed (buffer-string)))
	    (should-error (agentedit-review--replace-current session "usually") :type 'agentedit-review-stale)
	    (should (equal changed (buffer-string)))))))
    (agentedit-review-test--with-source (concat "Earlier.\n" (alist-get 'source f))
      (let* ((records (agentedit-review--scan-records (point-min)))
	     (session (agentedit-review--make-session :source (current-buffer) :records records)))
	(goto-char (point-min)) (insert "\\begin{verbatim}\n")
	(should-error (agentedit-review--replace-current session "usually") :type 'agentedit-review-stale)))
    (agentedit-review-test--with-source (concat "Earlier.\n" (alist-get 'source f))
      (let* ((records (agentedit-review--scan-records (point-min)))
	     (session (agentedit-review--make-session :source (current-buffer) :records records)))
	(goto-char (point-min)) (insert "Harmless. ")
	(agentedit-review--replace-current session "usually")
	(should (equal (buffer-string) (concat "Harmless. Earlier.\n" (alist-get 'accepted f))))))))

(ert-deftest agentedit-readable-adjacent-three-decisions-and-undo ()
  (let* ((f (agentedit-readable-test--fixture "word"))
         (frame (alist-get 'frame f))
         (second (replace-regexp-in-string "word" "second" frame t t))
         (third (replace-regexp-in-string "word" "third" frame t t))
         (source (concat "We " frame second third "finish.")))
    (dolist (choices '(("usually" "always" "usually") ("always" "usually" "always")))
      (agentedit-review-test--with-source source
	(let* ((records (agentedit-review--scan-records (point-min)))
	       (session (agentedit-review--make-session :source (current-buffer) :records records)))
	  (dotimes (index 3)
	    (setf (agentedit-review-session-index session) index)
	    (agentedit-review--replace-current session (nth index choices)))
	  (should (equal (buffer-string) (concat "We " (mapconcat #'identity choices " ") " finish.")))
	  (undo-only 1) (undo-more 1) (undo-more 1)
	  (should (equal (buffer-string) source)))))))

(ert-deftest agentedit-readable-undo-invalidates-rebased-neighbor ()
  (let* ((f (agentedit-readable-test--fixture "word")) (frame (alist-get 'frame f)))
    (agentedit-review-test--with-source
        (concat frame (replace-regexp-in-string "word" "next" frame t t) "tail")
      (let* ((records (agentedit-review--scan-records (point-min)))
             (session (agentedit-review--make-session :source (current-buffer) :records records)))
        (agentedit-review--replace-current session "usually")
        (undo-only 1)
        (setf (agentedit-review-session-index session) 1)
        (should-error (agentedit-review--replace-current session "usually") :type 'agentedit-review-stale)))))

(ert-deftest agentedit-readable-does-not-rebase-external-neighbor-change ()
  (let* ((f (agentedit-readable-test--fixture "word")) (frame (alist-get 'frame f)))
    (agentedit-review-test--with-source
        (concat frame (replace-regexp-in-string "word" "next" frame t t) "tail")
      (let* ((records (agentedit-review--scan-records (point-min)))
             (session (agentedit-review--make-session :source (current-buffer) :records records)))
        (goto-char (agentedit-review-record-start (cadr records)))
        (insert "external ")
        (should-error (agentedit-review--replace-current session "usually") :type 'agentedit-review-stale)))))

(ert-deftest agentedit-readable-empty-projection-label-is-outside-text ()
  (dolist (text '("" " \n\t"))
    (let ((buffer (agentedit-review--make-projection nil "original" text "empty")))
      (unwind-protect
          (with-current-buffer buffer
            (should (equal (buffer-string) text))
            (should (string-match-p (if (string-empty-p text) "empty" "whitespace only")
                                    (mapconcat #'identity header-line-format ""))))
        (kill-buffer buffer)))))

(ert-deftest agentedit-readable-file-coding-and-eof-roundtrip ()
  (dolist (coding '(utf-8-unix utf-8-dos))
    (dolist (side '(accepted rejected))
      (let* ((f (agentedit-readable-test--fixture "unicode"))
             (path (make-temp-file "agentedit-coding-" nil ".tex")) buffer)
        (unwind-protect
            (progn
              (let ((coding-system-for-write coding))
                (write-region (alist-get 'source f) nil path nil 'silent))
              (setq buffer (find-file-noselect path))
              (with-current-buffer buffer
                (latex-mode) (buffer-enable-undo)
                (let* ((records (agentedit-review--scan-records (point-min)))
                       (session (agentedit-review--make-session :source buffer :records records))
                       (saved-coding buffer-file-coding-system))
                  (agentedit-review--replace-current
                   session (alist-get (if (eq side 'accepted) 'proposed 'original) f))
                  (should (equal buffer-file-coding-system saved-coding))
                  (should (equal (encode-coding-string (buffer-string) buffer-file-coding-system)
                                 (encode-coding-string (alist-get side f) coding)))
                  (should-not (string-suffix-p "\n" (buffer-string))))))
          (when (buffer-live-p buffer)
            (with-current-buffer buffer (set-buffer-modified-p nil))
            (kill-buffer buffer))
          (delete-file path))))))


(ert-deftest agentedit-readable-narrow-controls-keep-unsaved-status ()
  (let ((source (generate-new-buffer " *readable status*")))
    (unwind-protect
        (with-temp-buffer
          (with-current-buffer source (insert "unsaved"))
          (setq-local agentedit-review--session
                      (agentedit-review--make-session :source source :sources (list source)))
          (dolist (width '(40 60 80))
            (cl-letf (((symbol-function 'window-body-width) (lambda (&rest _) width)))
              (agentedit-review--mode-line-format)
              (should (string-match-p "unsaved" agentedit-review--mode-status))
              (should (string-match-p "A accept.*R reject.*S skip.*q quit" agentedit-review--mode-controls))
              (should (<= (string-width (concat agentedit-review--mode-controls agentedit-review--mode-status agentedit-review--mode-counts)) width)))))
      (kill-buffer source))))

(ert-deftest agentedit-readable-atomic-rollback-preserves-frame-and-witnesses ()
  (let* ((frame (alist-get 'frame (agentedit-readable-test--fixture "word")))
         (source (concat frame (replace-regexp-in-string "word" "next" frame t t) "tail")))
    (agentedit-review-test--with-source source
      (let* ((records (agentedit-review--scan-records (point-min)))
             (session (agentedit-review--make-session :source (current-buffer) :records records))
             (witness (agentedit-review-record-left-context (cadr records)))
             (injected nil))
        ;; A buffer change hook exercises both interpreted and byte-compiled code.
        (add-hook 'before-change-functions
                  (lambda (begin end)
                    (when (and (= begin end) (not injected))
                      (setq injected t)
                      (error "injected frame insertion failure"))) nil t)
        (should-error (agentedit-review--replace-current session "usually"))
        (should injected)
        (should (equal (buffer-string) source))
        (should (equal (agentedit-review-record-left-context (cadr records)) witness))))))

(ert-deftest agentedit-readable-eof-and-separators-are-stale-witnesses ()
  (dolist (operation '(eof left right end-newline))
    (agentedit-review-test--with-source
        (alist-get 'source (agentedit-readable-test--fixture "empty-eof"))
      (let* ((records (agentedit-review--scan-records (point-min)))
             (record (car records))
             (session (agentedit-review--make-session :source (current-buffer) :records records)))
        (pcase operation
          ('eof (goto-char (point-max)) (insert "extra"))
          ('left (goto-char (agentedit-review-record-start record)) (delete-char 1))
          ('right (goto-char (point-min)) (search-forward "{}%") (delete-char -1))
          ('end-newline (goto-char (point-max)) (delete-char -1)))
        (let ((changed (buffer-string)))
          (should-error (agentedit-review--replace-current session "") :type 'agentedit-review-stale)
          (should (equal (buffer-string) changed)))))))

(ert-deftest agentedit-readable-real-ediff-actions-and-source-visit ()
  (let* ((source (generate-new-buffer " *Readable Ediff source*"))
         (frame (alist-get 'frame (agentedit-readable-test--fixture "word")))
         (second (replace-regexp-in-string "word" "second" frame t t))
         (third (replace-regexp-in-string "word" "third" frame t t))
         (ediff-window-setup-function #'ediff-setup-windows-plain)
         (ediff-keep-variants t))
    (unwind-protect
        (with-current-buffer source
          (insert (concat "We " frame second third "finish."))
          (if agentedit-review-test--use-auctex (LaTeX-mode) (latex-mode))
          (buffer-enable-undo) (goto-char (point-min))
          (agentedit-review t)
          (let* ((session (gethash source agentedit-review--sessions))
                 (control (agentedit-review-session-control session)))
            (with-current-buffer (agentedit-review-session-projection-a session)
              (should (equal (buffer-string) "always")))
            (with-current-buffer (agentedit-review-session-projection-b session)
              (should (equal (buffer-string) "usually")))
            (switch-to-buffer source)
            (goto-char (agentedit-review-record-start (car (agentedit-review-session-records session))))
            (should (search-backward "We " nil t))
            (should (eq session (gethash source agentedit-review--sessions)))
            (switch-to-buffer control) (agentedit-review--accept)
            (sleep-for 0.05)
            (with-current-buffer (agentedit-review-session-control session) (agentedit-review--reject))
            (sleep-for 0.05)
            (with-current-buffer (agentedit-review-session-control session) (agentedit-review--skip))
            (sleep-for 0.05)
            (should (eq (agentedit-review-session-state session) 'finished))
            (with-current-buffer source
              (should (equal (buffer-string) (concat "We usually always " third "finish."))))))
      (when (buffer-live-p source) (kill-buffer source)))))

(ert-deftest agentedit-readable-auctex-mixed-project-owns-the-correct-source ()
  (skip-unless agentedit-review-test--use-auctex)
  (let* ((directory (make-temp-file "agentedit-readable-project-" t))
         (master (expand-file-name "main.tex" directory))
         (child (expand-file-name "child.tex" directory))
         (master-text "\\agentedit{legacy}{Why.}{older}{newer}\n\\input{child}\n")
         (child-text (alist-get 'source (agentedit-readable-test--fixture "word")))
         (ediff-window-setup-function #'ediff-setup-windows-plain)
         (ediff-keep-variants t)
         sources session)
    (unwind-protect
        (progn
          (write-region master-text nil master nil 'silent)
          (write-region child-text nil child nil 'silent)
          (with-current-buffer (find-file-noselect master)
            (LaTeX-mode) (setq-local TeX-master t) (buffer-enable-undo)
            (agentedit-review)
            (setq session (gethash (current-buffer) agentedit-review--sessions)
                  sources (agentedit-review-session-sources session)))
          (should (= (length sources) 2))
          (should (equal (agentedit-review-test--ids (agentedit-review-session-records session)) '("legacy" "word")))
          (dolist (source sources)
            (should (eq (gethash source agentedit-review--sessions) session)))
          (with-current-buffer (agentedit-review-session-control session) (agentedit-review--accept))
          (sleep-for 0.05)
          (should (equal (buffer-file-name (agentedit-review-record-source (agentedit-review--current-record session))) child))
          (with-current-buffer (agentedit-review-session-control session) (agentedit-review--reject))
          (sleep-for 0.05)
          (with-current-buffer (find-buffer-visiting master)
            (should (equal (buffer-string) "newer\n\\input{child}\n")))
          (with-current-buffer (find-buffer-visiting child)
            (should (equal (buffer-string) (alist-get 'rejected (agentedit-readable-test--fixture "word")))))
          (dolist (source sources) (should-not (gethash source agentedit-review--sessions)))
          (should (equal (with-temp-buffer (insert-file-contents master) (buffer-string)) master-text))
          (should (equal (with-temp-buffer (insert-file-contents child) (buffer-string)) child-text))
          (let (records)
            (dolist (entry `((,master ,master-text)
                             (,child ,(replace-regexp-in-string "word" "legacy" child-text t t))))
              (with-current-buffer (find-buffer-visiting (car entry))
                (erase-buffer) (insert (cadr entry))
                (setq records (nconc records (agentedit-review--scan-records (point-min))))))
            (should-error (agentedit-review--validate-project-ids records) :type 'user-error)))
      (when session (agentedit-review--release session))
      (dolist (source sources)
        (when (buffer-live-p source)
          (with-current-buffer source (set-buffer-modified-p nil))
          (kill-buffer source)))
      (delete-directory directory t))))

(ert-deftest agentedit-readable-teardown-failure-reports-one-applied-decision ()
  (let ((source (generate-new-buffer " *readable partial source*"))
        (control (generate-new-buffer " *readable partial control*")))
    (unwind-protect
        (with-current-buffer source
          (insert (alist-get 'source (agentedit-readable-test--fixture "word")))
          (latex-mode) (buffer-enable-undo)
          (let ((session (agentedit-review--make-session
                          :source source :records (agentedit-review--scan-records (point-min))
                          :state 'reviewing :control control :lock-key source)))
            (puthash source session agentedit-review--sessions)
            (with-current-buffer control
              (setq-local agentedit-review--session session)
              (cl-letf (((symbol-function 'agentedit-review--ediff-really-quit)
                         (lambda () (error "injected frame teardown failure"))))
                (agentedit-review--accept)))
            (sleep-for 0.05)
            (should (equal (buffer-string) (alist-get 'accepted (agentedit-readable-test--fixture "word"))))
            (should (= (agentedit-review-session-accepted session) 1))
            (should (eq (agentedit-review-session-state session) 'partial-failure))
            (should-not (gethash source agentedit-review--sessions))
            (should-not (buffer-live-p control))))
      (when (buffer-live-p control) (kill-buffer control))
      (when (buffer-live-p source) (kill-buffer source)))))

(provide 'agentedit-readable-tests)
;;; agentedit-readable-tests.el ends here
